"""add team timestamps

Revision ID: 12e80416704e
Revises: 23a9b6aec616
Create Date: 2025-08-23 21:34:29.927799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e80416704e'
down_revision: Union[str, None] = '23a9b6aec616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False))
    op.add_column('teams', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False))
    op.create_foreign_key(None, 'teams', 'magic_items', ['magic_item_id'], ['id'])
    op.create_foreign_key(None, 'user_monsters', 'moves', ['move2_id'], ['id'])
    op.create_foreign_key(None, 'user_monsters', 'types', ['legacy_type_id'], ['id'])
    op.create_foreign_key(None, 'user_monsters', 'monsters', ['monster_id'], ['id'])
    op.create_foreign_key(None, 'user_monsters', 'moves', ['move4_id'], ['id'])
    op.create_foreign_key(None, 'user_monsters', 'moves', ['move1_id'], ['id'])
    op.create_foreign_key(None, 'user_monsters', 'moves', ['move3_id'], ['id'])
    op.create_foreign_key(None, 'user_monsters', 'personalities', ['personality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_monsters', type_='foreignkey')
    op.drop_constraint(None, 'user_monsters', type_='foreignkey')
    op.drop_constraint(None, 'user_monsters', type_='foreignkey')
    op.drop_constraint(None, 'user_monsters', type_='foreignkey')
    op.drop_constraint(None, 'user_monsters', type_='foreignkey')
    op.drop_constraint(None, 'user_monsters', type_='foreignkey')
    op.drop_constraint(None, 'user_monsters', type_='foreignkey')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'updated_at')
    op.drop_column('teams', 'created_at')
    # ### end Alembic commands ###
