"""rename additional columns by adding phy

Revision ID: 23855b9abe5a
Revises: e69293fc7ced
Create Date: 2025-06-30 21:30:36.801420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23855b9abe5a'
down_revision: Union[str, None] = 'e69293fc7ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalities', sa.Column('phy_atk_mod_pct', sa.Float(), nullable=False))
    op.add_column('personalities', sa.Column('phy_def_mod_pct', sa.Float(), nullable=False))
    op.drop_column('personalities', 'def_mod_pct')
    op.drop_column('personalities', 'atk_mod_pct')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalities', sa.Column('atk_mod_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('personalities', sa.Column('def_mod_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('personalities', 'phy_def_mod_pct')
    op.drop_column('personalities', 'phy_atk_mod_pct')
    # ### end Alembic commands ###
