"""baseline schema

Revision ID: 23a9b6aec616
Revises: 
Create Date: 2025-08-08 22:06:18.388102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23a9b6aec616'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_game_terms_localized_gin', 'game_terms', ['localized'], unique=False, postgresql_using='gin')
    op.create_table('monster_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_monster_species_localized_gin', 'monster_species', ['localized'], unique=False, postgresql_using='gin')
    op.create_table('personalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('hp_mod_pct', sa.Float(), nullable=False),
    sa.Column('phy_atk_mod_pct', sa.Float(), nullable=False),
    sa.Column('mag_atk_mod_pct', sa.Float(), nullable=False),
    sa.Column('phy_def_mod_pct', sa.Float(), nullable=False),
    sa.Column('mag_def_mod_pct', sa.Float(), nullable=False),
    sa.Column('spd_mod_pct', sa.Float(), nullable=False),
    sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_personalities_localized_gin', 'personalities', ['localized'], unique=False, postgresql_using='gin')
    op.create_table('traits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_traits_localized_gin', 'traits', ['localized'], unique=False, postgresql_using='gin')
    op.create_table('types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_types_localized_gin', 'types', ['localized'], unique=False, postgresql_using='gin')
    op.create_table('magic_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effect_code', sa.Enum('ENHANCE_SPELL', 'SUN_HEALING', 'FLARE_BURST', 'FLOW_SPELL', 'EVOLUTION_POWER', name='magic_effect_code_enum'), nullable=False),
    sa.Column('applies_to_type_id', sa.Integer(), nullable=True),
    sa.Column('effect_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['applies_to_type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_magic_items_localized_gin', 'magic_items', ['localized'], unique=False, postgresql_using='gin')
    op.create_table('monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('evolves_from_id', sa.Integer(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('form', sa.String(length=32), nullable=False),
    sa.Column('main_type_id', sa.Integer(), nullable=False),
    sa.Column('sub_type_id', sa.Integer(), nullable=True),
    sa.Column('default_legacy_type_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.Column('leader_potential', sa.Boolean(), nullable=False),
    sa.Column('is_leader_form', sa.Boolean(), nullable=False),
    sa.Column('base_hp', sa.Integer(), nullable=False),
    sa.Column('base_phy_atk', sa.Integer(), nullable=False),
    sa.Column('base_mag_atk', sa.Integer(), nullable=False),
    sa.Column('base_phy_def', sa.Integer(), nullable=False),
    sa.Column('base_mag_def', sa.Integer(), nullable=False),
    sa.Column('base_spd', sa.Integer(), nullable=False),
    sa.Column('preferred_attack_style', sa.Enum('PHYSICAL', 'MAGIC', 'BOTH', name='preferred_attack_style_enum'), nullable=False),
    sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['default_legacy_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['evolves_from_id'], ['monsters.id'], ),
    sa.ForeignKeyConstraint(['main_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['monster_species.id'], ),
    sa.ForeignKeyConstraint(['sub_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'form', name='uq_monster_name_form')
    )
    op.create_index('ix_monsters_localized_gin', 'monsters', ['localized'], unique=False, postgresql_using='gin')
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('move_type_id', sa.Integer(), nullable=True),
    sa.Column('move_category', sa.Enum('PHY_ATTACK', 'MAG_ATTACK', 'DEFENSE', 'STATUS', name='move_category_enum'), nullable=False),
    sa.Column('energy_cost', sa.Integer(), nullable=False),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('has_counter', sa.Boolean(), nullable=False),
    sa.Column('is_move_stone', sa.Boolean(), nullable=False),
    sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['move_type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_moves_localized_gin', 'moves', ['localized'], unique=False, postgresql_using='gin')
    op.create_table('type_effective_against',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('target_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('type_id', 'target_type_id')
    )
    op.create_table('type_weak_against',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('target_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('type_id', 'target_type_id')
    )
    op.create_table('legacy_moves',
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('monster_id', 'type_id')
    )
    op.create_table('monster_moves',
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['moves.id'], ),
    sa.PrimaryKeyConstraint('monster_id', 'move_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('magic_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['magic_item_id'], ['magic_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_monsters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_id', sa.Integer(), nullable=False),
    sa.Column('personality_id', sa.Integer(), nullable=False),
    sa.Column('legacy_type_id', sa.Integer(), nullable=False),
    sa.Column('move1_id', sa.Integer(), nullable=False),
    sa.Column('move2_id', sa.Integer(), nullable=False),
    sa.Column('move3_id', sa.Integer(), nullable=False),
    sa.Column('move4_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['legacy_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['monster_id'], ['monsters.id'], ),
    sa.ForeignKeyConstraint(['move1_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['move2_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['move3_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['move4_id'], ['moves.id'], ),
    sa.ForeignKeyConstraint(['personality_id'], ['personalities.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monster_instance_id', sa.Integer(), nullable=False),
    sa.Column('hp_boost', sa.Integer(), nullable=False),
    sa.Column('phy_atk_boost', sa.Integer(), nullable=False),
    sa.Column('mag_atk_boost', sa.Integer(), nullable=False),
    sa.Column('phy_def_boost', sa.Integer(), nullable=False),
    sa.Column('mag_def_boost', sa.Integer(), nullable=False),
    sa.Column('spd_boost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['monster_instance_id'], ['user_monsters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('talents')
    op.drop_table('user_monsters')
    op.drop_table('teams')
    op.drop_table('monster_moves')
    op.drop_table('legacy_moves')
    op.drop_table('type_weak_against')
    op.drop_table('type_effective_against')
    op.drop_index('ix_moves_localized_gin', table_name='moves', postgresql_using='gin')
    op.drop_table('moves')
    op.drop_index('ix_monsters_localized_gin', table_name='monsters', postgresql_using='gin')
    op.drop_table('monsters')
    op.drop_index('ix_magic_items_localized_gin', table_name='magic_items', postgresql_using='gin')
    op.drop_table('magic_items')
    op.drop_index('ix_types_localized_gin', table_name='types', postgresql_using='gin')
    op.drop_table('types')
    op.drop_index('ix_traits_localized_gin', table_name='traits', postgresql_using='gin')
    op.drop_table('traits')
    op.drop_index('ix_personalities_localized_gin', table_name='personalities', postgresql_using='gin')
    op.drop_table('personalities')
    op.drop_index('ix_monster_species_localized_gin', table_name='monster_species', postgresql_using='gin')
    op.drop_table('monster_species')
    op.drop_index('ix_game_terms_localized_gin', table_name='game_terms', postgresql_using='gin')
    op.drop_table('game_terms')
    # ### end Alembic commands ###
