"""Add localized columns

Revision ID: 53157bda4b56
Revises: c51b1debd417
Create Date: 2025-06-23 21:10:49.536658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53157bda4b56'
down_revision: Union[str, None] = 'c51b1debd417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_effective_against',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('target_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('type_id', 'target_type_id')
    )
    op.create_table('type_weak_against',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('target_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_type_id'], ['types.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['types.id'], ),
    sa.PrimaryKeyConstraint('type_id', 'target_type_id')
    )
    op.add_column('magic_items', sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index('ix_magic_items_localized_gin', 'magic_items', ['localized'], unique=False, postgresql_using='gin')
    op.add_column('monsters', sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index('ix_monsters_localized_gin', 'monsters', ['localized'], unique=False, postgresql_using='gin')
    op.add_column('moves', sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index('ix_moves_localized_gin', 'moves', ['localized'], unique=False, postgresql_using='gin')
    op.add_column('personalities', sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index('ix_personalities_localized_gin', 'personalities', ['localized'], unique=False, postgresql_using='gin')
    op.add_column('traits', sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index('ix_traits_localized_gin', 'traits', ['localized'], unique=False, postgresql_using='gin')
    op.add_column('types', sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index('ix_types_localized_gin', 'types', ['localized'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_types_localized_gin', table_name='types', postgresql_using='gin')
    op.drop_column('types', 'localized')
    op.drop_index('ix_traits_localized_gin', table_name='traits', postgresql_using='gin')
    op.drop_column('traits', 'localized')
    op.drop_index('ix_personalities_localized_gin', table_name='personalities', postgresql_using='gin')
    op.drop_column('personalities', 'localized')
    op.drop_index('ix_moves_localized_gin', table_name='moves', postgresql_using='gin')
    op.drop_column('moves', 'localized')
    op.drop_index('ix_monsters_localized_gin', table_name='monsters', postgresql_using='gin')
    op.drop_column('monsters', 'localized')
    op.drop_index('ix_magic_items_localized_gin', table_name='magic_items', postgresql_using='gin')
    op.drop_column('magic_items', 'localized')
    op.drop_table('type_weak_against')
    op.drop_table('type_effective_against')
    # ### end Alembic commands ###
