"""Add team_id in UserMonster table

Revision ID: 6bbefbd93365
Revises: bb27e1c861cc
Create Date: 2025-07-29 22:21:25.966874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bbefbd93365'
down_revision: Union[str, None] = 'bb27e1c861cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('magic_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['magic_item_id'], ['magic_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_monsters', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_monsters', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_monsters', type_='foreignkey')
    op.drop_column('user_monsters', 'team_id')
    op.drop_table('teams')
    # ### end Alembic commands ###
