"""Moves power nullable set to True

Revision ID: 796928774430
Revises: 76db55684c7d
Create Date: 2025-07-23 22:11:54.064249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796928774430'
down_revision: Union[str, None] = '76db55684c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moves', 'power',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('moves', 'power',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
