"""Monster sub_type nullable set to True

Revision ID: 8bd0b4ea53da
Revises: 796928774430
Create Date: 2025-07-24 11:53:39.403628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd0b4ea53da'
down_revision: Union[str, None] = '796928774430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monsters', 'sub_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monsters', 'sub_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
