"""Monster add unique constraint

Revision ID: bb27e1c861cc
Revises: 8bd0b4ea53da
Create Date: 2025-07-24 16:19:44.176961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb27e1c861cc'
down_revision: Union[str, None] = '8bd0b4ea53da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('monsters_name_key'), 'monsters', type_='unique')
    op.create_unique_constraint('uq_monster_name_form', 'monsters', ['name', 'form'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_monster_name_form', 'monsters', type_='unique')
    op.create_unique_constraint(op.f('monsters_name_key'), 'monsters', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
