"""Revise trait and leader logic

Revision ID: c3b49cd1a7fa
Revises: e957dcaa11da
Create Date: 2025-06-28 21:44:46.507958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3b49cd1a7fa'
down_revision: Union[str, None] = 'e957dcaa11da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('is_leader_form', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('monsters_trait_id_key'), 'monsters', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('monsters_trait_id_key'), 'monsters', ['trait_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('monsters', 'is_leader_form')
    # ### end Alembic commands ###
