"""Rename leader_tag to leader_potential

Revision ID: c51b1debd417
Revises: e0c0c61246eb
Create Date: 2025-06-14 15:36:30.476608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51b1debd417'
down_revision: Union[str, None] = 'e0c0c61246eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('leader_potential', sa.Boolean(), nullable=False))
    op.drop_column('monsters', 'leader_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('leader_tag', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('monsters', 'leader_potential')
    # ### end Alembic commands ###
