"""huge modification on schema based on new data

Revision ID: ce8e16d48635
Revises: 23855b9abe5a
Create Date: 2025-07-22 21:12:18.104767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce8e16d48635'
down_revision: Union[str, None] = '23855b9abe5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_game_terms_localized_gin', 'game_terms', ['localized'], unique=False, postgresql_using='gin')
    op.drop_column('magic_items', 'applies_to_leader_tag')
    op.add_column('moves', sa.Column('is_move_stone', sa.Boolean(), nullable=False))
    op.drop_column('user_monsters', 'has_leader_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_monsters', sa.Column('has_leader_tag', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('moves', 'is_move_stone')
    op.add_column('magic_items', sa.Column('applies_to_leader_tag', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index('ix_game_terms_localized_gin', table_name='game_terms', postgresql_using='gin')
    op.drop_table('game_terms')
    # ### end Alembic commands ###
