"""rename attack and defense columns by adding phy

Revision ID: e69293fc7ced
Revises: c3b49cd1a7fa
Create Date: 2025-06-30 21:28:30.736495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69293fc7ced'
down_revision: Union[str, None] = 'c3b49cd1a7fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monsters', sa.Column('base_phy_atk', sa.Integer(), nullable=False))
    op.add_column('monsters', sa.Column('base_phy_def', sa.Integer(), nullable=False))
    op.drop_column('monsters', 'base_def')
    op.drop_column('monsters', 'base_atk')
    op.add_column('talents', sa.Column('phy_atk_boost', sa.Integer(), nullable=False))
    op.add_column('talents', sa.Column('phy_def_boost', sa.Integer(), nullable=False))
    op.drop_column('talents', 'atk_boost')
    op.drop_column('talents', 'def_boost')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('talents', sa.Column('def_boost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('talents', sa.Column('atk_boost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('talents', 'phy_def_boost')
    op.drop_column('talents', 'phy_atk_boost')
    op.add_column('monsters', sa.Column('base_atk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('monsters', sa.Column('base_def', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('monsters', 'base_phy_def')
    op.drop_column('monsters', 'base_phy_atk')
    # ### end Alembic commands ###
