"""Add species table and additional fields in monster table

Revision ID: e957dcaa11da
Revises: 53157bda4b56
Create Date: 2025-06-28 00:52:28.829497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e957dcaa11da'
down_revision: Union[str, None] = '53157bda4b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monster_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('localized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_monster_species_localized_gin', 'monster_species', ['localized'], unique=False, postgresql_using='gin')
    op.add_column('monsters', sa.Column('species_id', sa.Integer(), nullable=False))
    op.add_column('monsters', sa.Column('evolves_from_id', sa.Integer(), nullable=True))
    op.add_column('monsters', sa.Column('form', sa.String(length=32), nullable=False))
    op.create_foreign_key(None, 'monsters', 'monster_species', ['species_id'], ['id'])
    op.create_foreign_key(None, 'monsters', 'monsters', ['evolves_from_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monsters', type_='foreignkey')
    op.drop_constraint(None, 'monsters', type_='foreignkey')
    op.drop_column('monsters', 'form')
    op.drop_column('monsters', 'evolves_from_id')
    op.drop_column('monsters', 'species_id')
    op.drop_index('ix_monster_species_localized_gin', table_name='monster_species', postgresql_using='gin')
    op.drop_table('monster_species')
    # ### end Alembic commands ###
